#include "desktop_shell/common/palette/hyprland_border_matugen.hpp"

#include "backends/hyprland/hyprland_backends.h"
#include "configuration/shell_config.hpp"

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <string>
#include <array>

namespace {

bool env_disables_hypr_matugen_border() {
  const char* e = std::getenv("EH_HYPR_MATUGEN_BORDER");
  if (e == nullptr || e[0] == '\0') return false;
  if (e[0] == '0' && e[1] == '\0') return true;
  std::array<char, 16> buf{};
  for (size_t i = 0; i < buf.size() - 1 && e[i] != '\0'; ++i) buf[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(e[i])));
  return std::strcmp(buf.data(), "off") == 0 || std::strcmp(buf.data(), "false") == 0 || std::strcmp(buf.data(), "no") == 0;
}

std::string hypr_rgba(float r, float g, float b, float a) {
  auto u = [](float x) -> int {
    return static_cast<int>(std::clamp(x, 0.f, 1.f) * 255.f + 0.5f);
  };
  std::array<char, 24> out;
  std::snprintf(out.data(), out.size(), "0x%02x%02x%02x%02x", u(a), u(r), u(g), u(b));
  return out.data();
}

bool keyword_set(const std::string& key_colon, const std::string& key_slash, const std::string& value) {
  auto try_key = [&](const std::string& key) -> bool {
    auto resp = hyprland_ipc_request("keyword " + key + " " + value);
    if (!resp) return false;
    while (!resp->empty() && static_cast<unsigned char>(resp->back()) <= ' ')
      resp->pop_back();
    return *resp == "ok";
  };
  return try_key(key_colon) || try_key(key_slash);
}

}

void sync_hyprland_border_matugen(const eh::config::ShellAppearance& a) {
  if (std::getenv("HYPRLAND_INSTANCE_SIGNATURE") == nullptr) return;
  if (env_disables_hypr_matugen_border()) return;
  if (!a.anyPaletteActive()) return;
  if (a.matugenThemingEnabled && !a.matugenOutputs.hyprland) return;

  const auto mc = eh::config::derived_chrome_colors(a);

  const std::string active1 = hypr_rgba(mc.accentR, mc.accentG, mc.accentB, 0.92f);
  const std::string active2 =
      hypr_rgba(mc.accentR * 0.82f, mc.accentG * 0.82f, mc.accentB * 0.82f, 0.70f);
  const std::string inactive =
      hypr_rgba(mc.outlineR, mc.outlineG, mc.outlineB, 0.42f);
  const std::string locked =
      hypr_rgba(mc.notifCriticalOutlineR, mc.notifCriticalOutlineG, mc.notifCriticalOutlineB, 1.0f);

  const std::string ac_gradient = active1 + " " + active2 + " 45deg";

  if (wspace::hyprland::hyprland_config_is_lua()) {
    const char* home = std::getenv("HOME");
    if (home) {
      const std::string dir = std::string(home) + "/.config/hypr/hyprland";
      std::filesystem::create_directories(dir);
      const std::string path = dir + "/colors.lua";
      const std::string content =
          "-- Generated by Event Horizon\n"
          "hl.config({\n"
          "  general = {\n"
          "    col = {\n"
          "      active_border   = { colors = { \"" + active1 + "\", \"" + active2 + "\" }, angle = 45 },\n"
          "      inactive_border = \"" + inactive + "\"\n"
          "    }\n"
          "  },\n"
          "  group = {\n"
          "    col = {\n"
          "      border_active          = { colors = { \"" + active1 + "\", \"" + active2 + "\" }, angle = 45 },\n"
          "      border_inactive        = \"" + inactive + "\",\n"
          "      border_locked_active   = \"" + locked + "\",\n"
          "      border_locked_inactive = \"" + inactive + "\"\n"
          "    },\n"
          "    groupbar = {\n"
          "      col = {\n"
          "        active          = { colors = { \"" + active1 + "\", \"" + active2 + "\" }, angle = 45 },\n"
          "        inactive        = \"" + inactive + "\",\n"
          "        locked_active   = \"" + locked + "\",\n"
          "        locked_inactive = \"" + inactive + "\"\n"
          "      }\n"
          "    }\n"
          "  }\n"
          "})\n";
      if (FILE* f = std::fopen(path.c_str(), "w")) {
        std::fwrite(content.data(), 1, content.size(), f);
        std::fclose(f);
      }
    }
    (void)hyprland_ipc_send("reload");
  } else {
    keyword_set("general:col.active_border", "general/col/active_border", ac_gradient);
    keyword_set("general:col.inactive_border", "general/col/inactive_border", inactive);
    keyword_set("group:col.border_active", "group/col/border_active", ac_gradient);
    keyword_set("group:col.border_inactive", "group/col/border_inactive", inactive);
    keyword_set("group:col.border_locked_active", "group/col/border_locked_active", locked);
    keyword_set("group:col.border_locked_inactive", "group/col/border_locked_inactive", inactive);
    keyword_set("group:groupbar:col.active", "group/groupbar/col/active", ac_gradient);
    keyword_set("group:groupbar:col.inactive", "group/groupbar/col/inactive", inactive);
    keyword_set("group:groupbar:col.locked_active", "group/groupbar/col/locked_active", locked);
    keyword_set("group:groupbar:col.locked_inactive", "group/groupbar/col/locked_inactive", inactive);
  }
}
